# Generated by Django 3.1.2 on 2020-11-23 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='handyman',
            options={'verbose_name_plural': 'handymen'},
        ),
        migrations.AlterModelOptions(
            name='techmembership',
            options={'verbose_name_plural': 'technician memberships'},
        ),
    ]
