# Generated by Django 3.1.2 on 2020-11-23 04:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20201123_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobbooking',
            name='schedule',
        ),
        migrations.AddField(
            model_name='jobbooking',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobbooking',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
