# Generated by Django 3.1.2 on 2020-11-21 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='contact_number',
        ),
    ]
